# Generated by Django 5.2.6 on 2026-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformadmin',
            name='access_code_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
