# Generated by Django 5.2.6 on 2026-08-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('account', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tariffs',
                'ordering': ('account', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on', models.DateField(db_index=True)),
                ('taken_at', models.DateTimeField()),
                ('account', models.CharField(db_index=True, max_length=255)),
                ('domain_id', models.CharField(blank=True, default='', max_length=64)),
                ('project_id', models.CharField(db_index=True, max_length=64)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('vms_total', models.PositiveIntegerField(default=0)),
                ('vms_running', models.PositiveIntegerField(default=0)),
                ('vcpus', models.PositiveIntegerField(default=0)),
                ('ram_mb', models.PositiveIntegerField(default=0)),
                ('ssd_gib', models.PositiveIntegerField(default=0)),
                ('hdd_gib', models.PositiveIntegerField(default=0)),
                ('unlabelled_gib', models.PositiveIntegerField(default=0)),
                ('elastic_ips', models.PositiveIntegerField(default=0)),
                ('snapshot_gib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'usage_snapshots',
                'ordering': ('-taken_on', 'project_name'),
                'unique_together': {('project_id', 'taken_on')},
            },
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('vcpu', 'vCPU'), ('ram_gb', 'RAM, GB'), ('ssd_gb', 'SSD, GB'), ('hdd_gb', 'HDD, GB'), ('elastic_ip', 'Elastic IP'), ('snapshot_gb', 'Snapshot storage, GB')], max_length=32)),
                ('price_per_month', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='billing.tariff')),
            ],
            options={
                'db_table': 'tariff_rates',
                'ordering': ('resource',),
                'unique_together': {('tariff', 'resource')},
            },
        ),
    ]
