# Generated by Django 5.2.6 on 2026-08-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_id', models.CharField(blank=True, default='', max_length=32, verbose_name='ИНН')),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('contract', models.CharField(blank=True, default='', max_length=120)),
                ('director', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_profiles',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('number_seq', models.PositiveIntegerField()),
                ('account', models.CharField(db_index=True, max_length=255)),
                ('domain_id', models.CharField(blank=True, default='', max_length=64)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('seller', models.JSONField(default=dict)),
                ('buyer', models.JSONField(default=dict)),
                ('days_measured', models.PositiveIntegerField(default=0)),
                ('days_in_period', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ('-period', 'account'),
                'unique_together': {('account', 'period')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=120)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ('resource',),
            },
        ),
    ]
