# Generated by Django 5.2.6 on 2026-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingprofile_invoice_invoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesnapshot',
            name='backup_snapshot_gib',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
